# Form implementation generated from reading ui file 'bo5loc.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bo5lock_widget(object):
    def setupUi(self, bo5lock_widget):
        bo5lock_widget.setObjectName("bo5lock_widget")
        bo5lock_widget.resize(220, 365)
        self.gridLayout_2 = QtWidgets.QGridLayout(bo5lock_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(bo5lock_widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.update_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.update_radioButton.setObjectName("update_radioButton")
        self.gridLayout.addWidget(self.update_radioButton, 6, 0, 1, 1)
        self.delete_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.delete_radioButton.setObjectName("delete_radioButton")
        self.gridLayout.addWidget(self.delete_radioButton, 7, 0, 1, 1)
        self.create_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.create_radioButton.setObjectName("create_radioButton")
        self.gridLayout.addWidget(self.create_radioButton, 4, 0, 1, 1)
        self.login_label = QtWidgets.QLabel(self.groupBox)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 2, 0, 1, 1)
        self.service_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.service_comboBox.setEditable(True)
        self.service_comboBox.setObjectName("service_comboBox")
        self.gridLayout.addWidget(self.service_comboBox, 1, 0, 1, 1)
        self.service_label = QtWidgets.QLabel(self.groupBox)
        self.service_label.setObjectName("service_label")
        self.gridLayout.addWidget(self.service_label, 0, 0, 1, 1)
        self.fetch_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.fetch_radioButton.setObjectName("fetch_radioButton")
        self.gridLayout.addWidget(self.fetch_radioButton, 5, 0, 1, 1)
        self.label_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.label_comboBox.setEditable(True)
        self.label_comboBox.setObjectName("label_comboBox")
        self.gridLayout.addWidget(self.label_comboBox, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.apply_pushButton = QtWidgets.QPushButton(bo5lock_widget)
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.gridLayout_2.addWidget(self.apply_pushButton, 1, 0, 1, 1)
        self.quit_pushButton = QtWidgets.QPushButton(bo5lock_widget)
        self.quit_pushButton.setObjectName("quit_pushButton")
        self.gridLayout_2.addWidget(self.quit_pushButton, 2, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(bo5lock_widget)
        self.status_label.setObjectName("status_label")
        self.gridLayout_2.addWidget(self.status_label, 3, 0, 1, 1)

        self.retranslateUi(bo5lock_widget)
        self.quit_pushButton.clicked.connect(bo5lock_widget.close)
        QtCore.QMetaObject.connectSlotsByName(bo5lock_widget)
        bo5lock_widget.setTabOrder(self.service_comboBox, self.label_comboBox)
        bo5lock_widget.setTabOrder(self.label_comboBox, self.create_radioButton)
        bo5lock_widget.setTabOrder(self.create_radioButton, self.fetch_radioButton)
        bo5lock_widget.setTabOrder(self.fetch_radioButton, self.update_radioButton)
        bo5lock_widget.setTabOrder(self.update_radioButton, self.delete_radioButton)
        bo5lock_widget.setTabOrder(self.delete_radioButton, self.apply_pushButton)
        bo5lock_widget.setTabOrder(self.apply_pushButton, self.quit_pushButton)

    def retranslateUi(self, bo5lock_widget):
        _translate = QtCore.QCoreApplication.translate
        bo5lock_widget.setWindowTitle(_translate("bo5lock_widget", "bo5lock ui"))
        self.groupBox.setTitle(_translate("bo5lock_widget", "bo5lock"))
        self.update_radioButton.setText(_translate("bo5lock_widget", "update"))
        self.delete_radioButton.setText(_translate("bo5lock_widget", "delete"))
        self.create_radioButton.setText(_translate("bo5lock_widget", "create"))
        self.login_label.setText(_translate("bo5lock_widget", "Label"))
        self.service_label.setText(_translate("bo5lock_widget", "Service"))
        self.fetch_radioButton.setText(_translate("bo5lock_widget", "fetch"))
        self.apply_pushButton.setText(_translate("bo5lock_widget", "apply"))
        self.quit_pushButton.setText(_translate("bo5lock_widget", "quit"))
        self.status_label.setText(_translate("bo5lock_widget", "status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bo5lock_widget = QtWidgets.QWidget()
    ui = Ui_bo5lock_widget()
    ui.setupUi(bo5lock_widget)
    bo5lock_widget.show()
    sys.exit(app.exec())
