# Form implementation generated from reading ui file 'bo5lock.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bo5lock_widget(object):
    def setupUi(self, bo5lock_widget):
        bo5lock_widget.setObjectName("bo5lock_widget")
        bo5lock_widget.resize(339, 433)
        self.gridLayout_2 = QtWidgets.QGridLayout(bo5lock_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(bo5lock_widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.kw_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.kw_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.kw_lineEdit.setObjectName("kw_lineEdit")
        self.gridLayout.addWidget(self.kw_lineEdit, 5, 0, 1, 1)
        self.service_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.service_comboBox.setEditable(True)
        self.service_comboBox.setObjectName("service_comboBox")
        self.gridLayout.addWidget(self.service_comboBox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.label_comboBox.setEditable(True)
        self.label_comboBox.setObjectName("label_comboBox")
        self.gridLayout.addWidget(self.label_comboBox, 3, 0, 1, 1)
        self.service_label = QtWidgets.QLabel(self.groupBox)
        self.service_label.setObjectName("service_label")
        self.gridLayout.addWidget(self.service_label, 0, 0, 1, 1)
        self.cmd_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.cmd_comboBox.setObjectName("cmd_comboBox")
        self.cmd_comboBox.addItem("")
        self.cmd_comboBox.addItem("")
        self.cmd_comboBox.addItem("")
        self.cmd_comboBox.addItem("")
        self.gridLayout.addWidget(self.cmd_comboBox, 7, 0, 1, 1)
        self.login_label = QtWidgets.QLabel(self.groupBox)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.apply_pushButton = QtWidgets.QPushButton(bo5lock_widget)
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.gridLayout_2.addWidget(self.apply_pushButton, 1, 0, 1, 1)
        self.quit_pushButton = QtWidgets.QPushButton(bo5lock_widget)
        self.quit_pushButton.setObjectName("quit_pushButton")
        self.gridLayout_2.addWidget(self.quit_pushButton, 2, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(bo5lock_widget)
        self.status_label.setObjectName("status_label")
        self.gridLayout_2.addWidget(self.status_label, 3, 0, 1, 1)
        self.status_textEdit = QtWidgets.QTextEdit(bo5lock_widget)
        self.status_textEdit.setEnabled(True)
        self.status_textEdit.setReadOnly(True)
        self.status_textEdit.setObjectName("status_textEdit")
        self.gridLayout_2.addWidget(self.status_textEdit, 4, 0, 1, 1)

        self.retranslateUi(bo5lock_widget)
        self.quit_pushButton.clicked.connect(bo5lock_widget.close)
        QtCore.QMetaObject.connectSlotsByName(bo5lock_widget)
        bo5lock_widget.setTabOrder(self.service_comboBox, self.label_comboBox)
        bo5lock_widget.setTabOrder(self.label_comboBox, self.kw_lineEdit)
        bo5lock_widget.setTabOrder(self.kw_lineEdit, self.cmd_comboBox)
        bo5lock_widget.setTabOrder(self.cmd_comboBox, self.apply_pushButton)
        bo5lock_widget.setTabOrder(self.apply_pushButton, self.quit_pushButton)
        bo5lock_widget.setTabOrder(self.quit_pushButton, self.status_textEdit)

    def retranslateUi(self, bo5lock_widget):
        _translate = QtCore.QCoreApplication.translate
        bo5lock_widget.setWindowTitle(_translate("bo5lock_widget", "bo5lock ui"))
        self.groupBox.setTitle(_translate("bo5lock_widget", "bo5lock"))
        self.label.setText(_translate("bo5lock_widget", "Command"))
        self.service_label.setText(_translate("bo5lock_widget", "Service"))
        self.cmd_comboBox.setItemText(0, _translate("bo5lock_widget", "create"))
        self.cmd_comboBox.setItemText(1, _translate("bo5lock_widget", "fetch"))
        self.cmd_comboBox.setItemText(2, _translate("bo5lock_widget", "update"))
        self.cmd_comboBox.setItemText(3, _translate("bo5lock_widget", "delete"))
        self.login_label.setText(_translate("bo5lock_widget", "Label"))
        self.label_2.setText(_translate("bo5lock_widget", "kw"))
        self.apply_pushButton.setText(_translate("bo5lock_widget", "apply"))
        self.quit_pushButton.setText(_translate("bo5lock_widget", "quit"))
        self.status_label.setText(_translate("bo5lock_widget", "status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bo5lock_widget = QtWidgets.QWidget()
    ui = Ui_bo5lock_widget()
    ui.setupUi(bo5lock_widget)
    bo5lock_widget.show()
    sys.exit(app.exec())
